title: "Welcome to docs.openwrt.melmac.net!"
description: "stangri's OpenWrt Packages Documentation."
url: "https://docs.openwrt.melmac.net"
header_pages:
  - adblock-fast/
  - https-dns-proxy/
  - pbr/
theme: minima
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/stangri" }
    - {
        platform: facebook,
        user_url: "https://www.facebook.com/stangri.openwrt/",
      }
    - { platform: twitter, user_url: "https://twitter.com/stangri" }
plugins:
  - jemoji
